name: "Continuous Deployment"
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

concurrency: ${{ github.event_name == 'push' && 'main' || github.run_id }}
jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - if: github.event_name == 'push'
        uses: docker/bake-action@v4
        with:
          push: true
